config/routes.rb
GoalApp::Application.routes.draw do

  resources :users, only: [:new, :create, :show] do
    resources :user_comments, :only => [:new]
  end

  resource :session, only: [:new, :create, :destroy]

  resources :goals do
    resources :goal_comments, only: [:new]
  end

  resources :user_comments, :only => [:create]
  resources :goal_comments, :only => [:create]
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  validates :user_id, :content, :goal_type, :goal_status, presence: true

  belongs_to(
    :user,
    class_name: "User",
    foreign_key: :user_id,
    primary_key: :id
  )

  has_many :comments_received,
    class_name: "GoalComment",
    foreign_key: :subject_id,
    primary_key: :id

  

end

app/models/goal_comment.rb
class GoalComment < ActiveRecord::Base
  validates :commenter_id, :subject_id, :comment, presence: true

  belongs_to :commenter,
    class_name: "User",
    foreign_key: :commenter_id,
    primary_key: :id

  belongs_to :goal,
    class_name: "Goal",
    foreign_key: :subject_id,
    primary_key: :id

    has_one :goal_owner,
    through: :goal,
    source: :user

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :session_token, :password_digest, presence: true
  validates :password, length: {minimum: 6, allow_nil: true}

  after_initialize :ensure_session_token

  attr_reader :password

  has_many(
  :goals,
  foreign_key: :user_id,
  primary_key: :id,
  class_name: "Goal"
  )

  has_many :comments_received,
    class_name: "UserComment",
    foreign_key: :subject_id,
    primary_key: :id

  has_many :user_comments_made,
    class_name: "UserComment",
    foreign_key: :commenter_id,
    primary_key: :id

  has_many :goal_comments_made,
    class_name: "GoalComment",
    foreign_key: :commenter_id,
    primary_key: :id

  def self.find_by_credentials(username, password)
    @user = User.find_by(username: username)
    return nil unless @user && @user.is_password?(password)

    @user
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end

end

app/models/user_comment.rb
class UserComment < ActiveRecord::Base
  validates :commenter_id, :subject_id, :comment, presence: true

  belongs_to :commenter,
    class_name: "User",
    foreign_key: :commenter_id,
    primary_key: :id

  belongs_to :subject,
    class_name: "User",
    foreign_key: :subject_id,
    primary_key: :id


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  helper_method :current_user, :signed_in?

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def signed_in?
    !!current_user
  end

  def sign_in(user)
    user.reset_session_token
    session[:session_token] = user.session_token
  end

  def sign_out
    current_user.reset_session_token
    session[:session_token] = nil
  end

  private

  def require_signed_in
    redirect_to new_session_url unless signed_in?
  end
end

app/controllers/goal_comments_controller.rb
class GoalCommentsController < ApplicationController

  def new
    @goal_comment = current_user.goal_comments_made.new
  end

  def create
    @goal_comment = current_user.goal_comments_made.new(comment_params)
    if @goal_comment.save
      flash[:notices] = ["Comment Submitted"]
      redirect_to user_url(@goal_comment.goal_owner)
    else
      flash[:errors] = @goal_comment.errors.full_messages
      render :new
    end
  end


private

  def comment_params
    params.require(:goal_comment).permit(:comment, :subject_id)
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :require_signed_in

  def index
    render :index
  end

  def new
    @goal = current_user.goals.new
  end

  def create
    @goal = current_user.goals.new(goal_params)
    @goal.goal_status = "Not Completed"
    if @goal.save
      redirect_to goals_url
    else
      flash[:errors] = @goal.errors.full_messages
      render :new
    end
  end

  def edit
    @goal = Goal.find(params[:id])
  end

  def update
    @goal = Goal.find(params[:id])
    if @goal.update(goal_params)
      flash[:notices] = ["Goal Updated"]
      redirect_to user_url(@goal.user_id)
    else
      flash[:errors] = @goal.errors.full_messages
      render :edit
    end
  end

  def destroy
    @goal = Goal.find(params[:id])
    @goal.destroy
    redirect_to user_url(params[:user_id])
  end

  private

  def goal_params
    params.require(:goal).permit(:content, :goal_type, :goal_status)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

   def new

   end

   def create
     user = User.find_by_credentials(
     params[:user][:username],
     params[:user][:password])

     if user
       sign_in(user)
       redirect_to goals_url
     else
       flash[:errors] = ["Invalid username or password"]
       render :new
     end
   end

   def destroy
     sign_out
     redirect_to new_session_url
   end

end

app/controllers/user_comments_controller.rb
class UserCommentsController < ApplicationController

    def new
      @user_comment = current_user.user_comments_made.new
    end

    def create
      @user_comment = current_user.user_comments_made.new(comment_params)
      if @user_comment.save
        flash[:notices] = ["Comment Submitted"]
        redirect_to user_url(@user_comment.subject)
      else
        flash[:errors] = @user_comment.errors.full_messages
        render :new
      end
    end


  private

    def comment_params
      params.require(:user_comment).permit(:comment, :subject_id)
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
      @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in(@user)
      redirect_to goals_url
    else
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def form_auth_token
    "<input
      type=\"hidden\"
      name=\"authenticity_token\"
      value=\"#{form_authenticity_token}\">".html_safe
  end
  
end

app/views/goal_comments/new.html.erb
<h1> Leave a Comment</h1>

<form action="<%= goal_comments_url %>" method="post">
  <%= form_auth_token %>
  <label for="comment">Comment</label>
  <input type="hidden" name="goal_comment[subject_id]" value="<%=params[:goal_id]%>">
  <textarea id="comment" name="goal_comment[comment]"></textarea>
  <button>Make Comment</button>
</form>

app/views/goals/edit.html.erb
<h1>Edit Goal</h1>

<form action="<%= goal_url(@goal) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <%= form_auth_token %>
  <label for="goal_content">Content</label>
  <input type="textarea" id="goal_content" name="goal[content]" value="<%= @goal.content%>">

  <label for="goal_type_public">Public</label>
    <input type="radio" name="goal[goal_type]" id="goal_type_public" value="Public" <%= checked="checked" if @goal.goal_type == "Public" %>>
  <label for="goal_type_private">Private</label>
    <input type="radio" name="goal[goal_type]" id="goal_type_private" value="Private"<%= checked="checked" if @goal.goal_type == "Private" %>>

  <label for="goal_status_completed">Completed</label>
    <input type="radio" name="goal[goal_status]" id="goal_status_completed" value="Completed" <%= checked="checked" if @goal.goal_status == "Completed" %>>
  <label for="goal_status_not_completed">Not Completed</label>
    <input type="radio" name="goal[goal_status]" id="goal_status_not_completed" value="Not Completed" <%= checked="checked" if @goal.goal_status == "Not Completed" %>>


  <button>Update Goal</button>
</form>

<a href="<%= goals_url %>">Back to Goals Index</a>

<form action="<%= goal_url(@goal) %>" method="POST">
  <input type="hidden" name="user_id" value="<%=@goal.user_id%>">
  <input type="hidden" name="_method" value="DELETE">
  <%= form_auth_token %>
  <button>Delete Goal</button>
</form>

app/views/goals/index.html.erb
<h1><%= current_user.username %></h1>
<form action="<%= new_goal_url %>" method="get">
  <%= form_auth_token %>
  <button>New Goal</button>

</form>

<ul>
  <% Goal.where(goal_type: "Public").each do |goal|%>
    <li>
      <%= goal.content %> by <a href="<%= user_url(goal.user)%>"><%= goal.user.username %></a> Status: <%= goal.goal_status %>
    </li>
  <% end %>
</ul>

app/views/goals/new.html.erb
<h1>New Goal</h1>

<form action="<%= goals_url %>" method="post">
  <%= form_auth_token %>
  <label for="goal_content">Content</label>
  <input type="textarea" id="goal_content" name="goal[content]" value="<%= @goal.content%>">

  <label for="goal_type_public">Public</label>
    <input type="radio" name="goal[goal_type]" id="goal_type_public" value="Public" checked="checked">
  <label for="goal_type_private">Private</label>
    <input type="radio" name="goal[goal_type]" id="goal_type_private" value="Private">

  <button>Create Goal</button>
</form>

<a href="<%= goals_url %>">Back to Goals Index</a>

app/views/layouts/_buttons.html.erb
<% if signed_in? %>
<form action="<%=session_url%>" method="post">
  <input type="hidden" name="_method" value="DELETE">
  <%= form_auth_token %>
  <button>Sign Out</button>
</form>

<% else %>
<form action= "<%=new_session_url%>" method="get">
  <%= form_auth_token %>
  <button>Sign In</button>
</form>
<a href="<%= new_user_url %>">Sign Up</a>
<% end %>

app/views/layouts/_errors.html.erb
<%= flash[:errors].join("<br>").html_safe if flash[:errors] %>

app/views/layouts/_notices.html.erb
<%= flash[:notices].join("<br>").html_safe if flash[:notice] %>

app/views/layouts/_profile.html.erb
<% if signed_in? %>
  <a href="<%= user_url(current_user) %>">My Profile</a>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoalApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/profile' %>
<%= render 'layouts/buttons' %>
<%= render 'layouts/errors' %>
<%= render 'layouts/notices' %>
<%= yield %>

</body>
</html>

app/views/session/new.html.erb
<h1>Sign In</h1>
<form action="<%= session_url %>" method="post">
  <%= form_auth_token %>
  <label for="username">Username</label>
  <input id="username" type="text" name="user[username]">
  <br>
  <label for="password">Password</label>
  <input id="password" type="password" name="user[password]">

  <button>Sign In</button>
</form>

app/views/user_comments/new.html.erb
<h1> Leave a Comment</h1>

<form action="<%= user_comments_url %>" method="post">
  <%= form_auth_token %>
  <label for="comment">Comment</label>
  <input type="hidden" name="user_comment[subject_id]" value="<%=params[:user_id]%>">
  <textarea id="comment" name="user_comment[comment]"></textarea>
  <button>Make Comment</button>
</form>

app/views/users/_goal_comments.html.erb
<ul>
  <% goal.comments_received.each do |comment| %>
    <li> <%=comment.comment%> says <%=comment.commenter.username%> </li>
  <% end %>
</ul>
<a href="<%=new_goal_goal_comment_url(goal)%>">Comment on <%=goal.content%></a>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<form action="<%= users_url %>" method="post">
  <%= form_auth_token %>
  <label for="username">Username</label>
  <input id="username" type="text" name="user[username]" value="<%=@user.username%>">
  <br>
  <label for="password">Password</label>
  <input id="password" type="password" name="user[password]">

  <button>Create User</button>
</form>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>
<ul>
  <% @user.comments_received.each do |comment| %>
    <li> <%=comment.comment%> says <%=comment.commenter.username%> </li>
  <% end %>
</ul>
<a href="<%=new_user_user_comment_url(@user)%>">Comment on <%=@user.username%></a>

<ul>
  <% Goal.where(goal_type: "Public").where(user_id: params[:id]).each do |goal| %>
    <li>
      <% if current_user.id == params[:id].to_i %>
        <a href="<%=edit_goal_url(goal)%>"><%= goal.content %></a>
        <% else %>
        <%= goal.content %>
        <% end %>
      Status: <%= goal.goal_status %>
      <%= render "goal_comments", goal: goal  %>
    </li>
  <% end %>

  <% if current_user.id == params[:id].to_i %>
    <% current_user.goals.where(goal_type: "Private").each do |goal| %>
      <li>
        <a href="<%=edit_goal_url(goal)%>"><%= goal.content %></a> Status: <%= goal.goal_status %>
        <%= render "goal_comments", goal: goal  %>
      </li>
    <% end %>
  <% end %>
</ul>

<br>
<% if current_user.id == params[:id].to_i %>
<form action="<%= new_goal_url %>" method="get">
  <%= form_auth_token %>
  <button>New Goal</button>

</form>
<% end %>

<a href="<%= goals_url %>">Back to Goals Index</a>